/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.3.8
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.Forbidden = factory(root.EveSwaggerInterface.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Forbidden model module.
   * @module model/Forbidden
   * @version 1.3.8
   */

  /**
   * Constructs a new <code>Forbidden</code>.
   * Forbidden model
   * @alias module:model/Forbidden
   * @class
   * @param error {String} Forbidden message
   */
  var exports = function(error) {
    this.error = error;
  };

  /**
   * Constructs a <code>Forbidden</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Forbidden} obj Optional instance to populate.
   * @return {module:model/Forbidden} The populated <code>Forbidden</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('error'))
        obj.error = ApiClient.convertToType(data['error'], 'String');
      if (data.hasOwnProperty('sso_status'))
        obj.ssoStatus = ApiClient.convertToType(data['sso_status'], 'Number');
    }
    return obj;
  }

  /**
   * Forbidden message
   * @member {String} error
   */
  exports.prototype.error = undefined;

  /**
   * status code received from SSO
   * @member {Number} ssoStatus
   */
  exports.prototype.ssoStatus = undefined;

  return exports;

}));
