/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.3.8
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetCorporationsCorporationIdContracts200Ok = factory(root.EveSwaggerInterface.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GetCorporationsCorporationIdContracts200Ok model module.
   * @module model/GetCorporationsCorporationIdContracts200Ok
   * @version 1.3.8
   */

  /**
   * Constructs a new <code>GetCorporationsCorporationIdContracts200Ok</code>.
   * 200 ok object
   * @alias module:model/GetCorporationsCorporationIdContracts200Ok
   * @class
   * @param acceptorId {Number} Who will accept the contract
   * @param assigneeId {Number} ID to whom the contract is assigned, can be corporation or character ID
   * @param availability {module:model/GetCorporationsCorporationIdContracts200Ok.AvailabilityEnum} To whom the contract is available
   * @param contractId {Number} contract_id integer
   * @param dateExpired {Date} Expiration date of the contract
   * @param dateIssued {Date} Сreation date of the contract
   * @param forCorporation {Boolean} true if the contract was issued on behalf of the issuer's corporation
   * @param issuerCorporationId {Number} Character's corporation ID for the issuer
   * @param issuerId {Number} Character ID for the issuer
   * @param status {module:model/GetCorporationsCorporationIdContracts200Ok.StatusEnum} Status of the the contract
   * @param type {module:model/GetCorporationsCorporationIdContracts200Ok.TypeEnum} Type of the contract
   */
  var exports = function(acceptorId, assigneeId, availability, contractId, dateExpired, dateIssued, forCorporation, issuerCorporationId, issuerId, status, type) {
    this.acceptorId = acceptorId;
    this.assigneeId = assigneeId;
    this.availability = availability;
    this.contractId = contractId;
    this.dateExpired = dateExpired;
    this.dateIssued = dateIssued;
    this.forCorporation = forCorporation;
    this.issuerCorporationId = issuerCorporationId;
    this.issuerId = issuerId;
    this.status = status;
    this.type = type;
  };

  /**
   * Constructs a <code>GetCorporationsCorporationIdContracts200Ok</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCorporationsCorporationIdContracts200Ok} obj Optional instance to populate.
   * @return {module:model/GetCorporationsCorporationIdContracts200Ok} The populated <code>GetCorporationsCorporationIdContracts200Ok</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('acceptor_id'))
        obj.acceptorId = ApiClient.convertToType(data['acceptor_id'], 'Number');
      if (data.hasOwnProperty('assignee_id'))
        obj.assigneeId = ApiClient.convertToType(data['assignee_id'], 'Number');
      if (data.hasOwnProperty('availability'))
        obj.availability = ApiClient.convertToType(data['availability'], 'String');
      if (data.hasOwnProperty('buyout'))
        obj.buyout = ApiClient.convertToType(data['buyout'], 'Number');
      if (data.hasOwnProperty('collateral'))
        obj.collateral = ApiClient.convertToType(data['collateral'], 'Number');
      if (data.hasOwnProperty('contract_id'))
        obj.contractId = ApiClient.convertToType(data['contract_id'], 'Number');
      if (data.hasOwnProperty('date_accepted'))
        obj.dateAccepted = ApiClient.convertToType(data['date_accepted'], 'Date');
      if (data.hasOwnProperty('date_completed'))
        obj.dateCompleted = ApiClient.convertToType(data['date_completed'], 'Date');
      if (data.hasOwnProperty('date_expired'))
        obj.dateExpired = ApiClient.convertToType(data['date_expired'], 'Date');
      if (data.hasOwnProperty('date_issued'))
        obj.dateIssued = ApiClient.convertToType(data['date_issued'], 'Date');
      if (data.hasOwnProperty('days_to_complete'))
        obj.daysToComplete = ApiClient.convertToType(data['days_to_complete'], 'Number');
      if (data.hasOwnProperty('end_location_id'))
        obj.endLocationId = ApiClient.convertToType(data['end_location_id'], 'Number');
      if (data.hasOwnProperty('for_corporation'))
        obj.forCorporation = ApiClient.convertToType(data['for_corporation'], 'Boolean');
      if (data.hasOwnProperty('issuer_corporation_id'))
        obj.issuerCorporationId = ApiClient.convertToType(data['issuer_corporation_id'], 'Number');
      if (data.hasOwnProperty('issuer_id'))
        obj.issuerId = ApiClient.convertToType(data['issuer_id'], 'Number');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
      if (data.hasOwnProperty('reward'))
        obj.reward = ApiClient.convertToType(data['reward'], 'Number');
      if (data.hasOwnProperty('start_location_id'))
        obj.startLocationId = ApiClient.convertToType(data['start_location_id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('volume'))
        obj.volume = ApiClient.convertToType(data['volume'], 'Number');
    }
    return obj;
  }

  /**
   * Who will accept the contract
   * @member {Number} acceptorId
   */
  exports.prototype.acceptorId = undefined;

  /**
   * ID to whom the contract is assigned, can be corporation or character ID
   * @member {Number} assigneeId
   */
  exports.prototype.assigneeId = undefined;

  /**
   * To whom the contract is available
   * @member {module:model/GetCorporationsCorporationIdContracts200Ok.AvailabilityEnum} availability
   */
  exports.prototype.availability = undefined;

  /**
   * Buyout price (for Auctions only)
   * @member {Number} buyout
   */
  exports.prototype.buyout = undefined;

  /**
   * Collateral price (for Couriers only)
   * @member {Number} collateral
   */
  exports.prototype.collateral = undefined;

  /**
   * contract_id integer
   * @member {Number} contractId
   */
  exports.prototype.contractId = undefined;

  /**
   * Date of confirmation of contract
   * @member {Date} dateAccepted
   */
  exports.prototype.dateAccepted = undefined;

  /**
   * Date of completed of contract
   * @member {Date} dateCompleted
   */
  exports.prototype.dateCompleted = undefined;

  /**
   * Expiration date of the contract
   * @member {Date} dateExpired
   */
  exports.prototype.dateExpired = undefined;

  /**
   * Сreation date of the contract
   * @member {Date} dateIssued
   */
  exports.prototype.dateIssued = undefined;

  /**
   * Number of days to perform the contract
   * @member {Number} daysToComplete
   */
  exports.prototype.daysToComplete = undefined;

  /**
   * End location ID (for Couriers contract)
   * @member {Number} endLocationId
   */
  exports.prototype.endLocationId = undefined;

  /**
   * true if the contract was issued on behalf of the issuer's corporation
   * @member {Boolean} forCorporation
   */
  exports.prototype.forCorporation = undefined;

  /**
   * Character's corporation ID for the issuer
   * @member {Number} issuerCorporationId
   */
  exports.prototype.issuerCorporationId = undefined;

  /**
   * Character ID for the issuer
   * @member {Number} issuerId
   */
  exports.prototype.issuerId = undefined;

  /**
   * Price of contract (for ItemsExchange and Auctions)
   * @member {Number} price
   */
  exports.prototype.price = undefined;

  /**
   * Remuneration for contract (for Couriers only)
   * @member {Number} reward
   */
  exports.prototype.reward = undefined;

  /**
   * Start location ID (for Couriers contract)
   * @member {Number} startLocationId
   */
  exports.prototype.startLocationId = undefined;

  /**
   * Status of the the contract
   * @member {module:model/GetCorporationsCorporationIdContracts200Ok.StatusEnum} status
   */
  exports.prototype.status = undefined;

  /**
   * Title of the contract
   * @member {String} title
   */
  exports.prototype.title = undefined;

  /**
   * Type of the contract
   * @member {module:model/GetCorporationsCorporationIdContracts200Ok.TypeEnum} type
   */
  exports.prototype.type = undefined;

  /**
   * Volume of items in the contract
   * @member {Number} volume
   */
  exports.prototype.volume = undefined;


  /**
   * Allowed values for the <code>availability</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AvailabilityEnum = {
    /**
     * value: "public"
     * @const
     */
    _public: "public",

    /**
     * value: "personal"
     * @const
     */
    personal: "personal",

    /**
     * value: "corporation"
     * @const
     */
    corporation: "corporation",

    /**
     * value: "alliance"
     * @const
     */
    alliance: "alliance"
  };


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "outstanding"
     * @const
     */
    outstanding: "outstanding",

    /**
     * value: "in_progress"
     * @const
     */
    inProgress: "in_progress",

    /**
     * value: "finished_issuer"
     * @const
     */
    finishedIssuer: "finished_issuer",

    /**
     * value: "finished_contractor"
     * @const
     */
    finishedContractor: "finished_contractor",

    /**
     * value: "finished"
     * @const
     */
    finished: "finished",

    /**
     * value: "cancelled"
     * @const
     */
    cancelled: "cancelled",

    /**
     * value: "rejected"
     * @const
     */
    rejected: "rejected",

    /**
     * value: "failed"
     * @const
     */
    failed: "failed",

    /**
     * value: "deleted"
     * @const
     */
    deleted: "deleted",

    /**
     * value: "reversed"
     * @const
     */
    reversed: "reversed"
  };


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "unknown"
     * @const
     */
    unknown: "unknown",

    /**
     * value: "item_exchange"
     * @const
     */
    itemExchange: "item_exchange",

    /**
     * value: "auction"
     * @const
     */
    auction: "auction",

    /**
     * value: "courier"
     * @const
     */
    courier: "courier",

    /**
     * value: "loan"
     * @const
     */
    loan: "loan"
  };

  return exports;

}));
