/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.3.8
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetCorporationCorporationIdMiningObserversObserverId200Ok = factory(root.EveSwaggerInterface.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GetCorporationCorporationIdMiningObserversObserverId200Ok model module.
   * @module model/GetCorporationCorporationIdMiningObserversObserverId200Ok
   * @version 1.3.8
   */

  /**
   * Constructs a new <code>GetCorporationCorporationIdMiningObserversObserverId200Ok</code>.
   * 200 ok object
   * @alias module:model/GetCorporationCorporationIdMiningObserversObserverId200Ok
   * @class
   * @param characterId {Number} The character that did the mining 
   * @param lastUpdated {Date} last_updated string
   * @param quantity {Number} quantity integer
   * @param recordedCorporationId {Number} The corporation id of the character at the time data was recorded. 
   * @param typeId {Number} type_id integer
   */
  var exports = function(characterId, lastUpdated, quantity, recordedCorporationId, typeId) {
    this.characterId = characterId;
    this.lastUpdated = lastUpdated;
    this.quantity = quantity;
    this.recordedCorporationId = recordedCorporationId;
    this.typeId = typeId;
  };

  /**
   * Constructs a <code>GetCorporationCorporationIdMiningObserversObserverId200Ok</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCorporationCorporationIdMiningObserversObserverId200Ok} obj Optional instance to populate.
   * @return {module:model/GetCorporationCorporationIdMiningObserversObserverId200Ok} The populated <code>GetCorporationCorporationIdMiningObserversObserverId200Ok</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('character_id'))
        obj.characterId = ApiClient.convertToType(data['character_id'], 'Number');
      if (data.hasOwnProperty('last_updated'))
        obj.lastUpdated = ApiClient.convertToType(data['last_updated'], 'Date');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
      if (data.hasOwnProperty('recorded_corporation_id'))
        obj.recordedCorporationId = ApiClient.convertToType(data['recorded_corporation_id'], 'Number');
      if (data.hasOwnProperty('type_id'))
        obj.typeId = ApiClient.convertToType(data['type_id'], 'Number');
    }
    return obj;
  }

  /**
   * The character that did the mining 
   * @member {Number} characterId
   */
  exports.prototype.characterId = undefined;

  /**
   * last_updated string
   * @member {Date} lastUpdated
   */
  exports.prototype.lastUpdated = undefined;

  /**
   * quantity integer
   * @member {Number} quantity
   */
  exports.prototype.quantity = undefined;

  /**
   * The corporation id of the character at the time data was recorded. 
   * @member {Number} recordedCorporationId
   */
  exports.prototype.recordedCorporationId = undefined;

  /**
   * type_id integer
   * @member {Number} typeId
   */
  exports.prototype.typeId = undefined;

  return exports;

}));
