/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.3.8
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetContractsPublicItemsContractId200Ok = factory(root.EveSwaggerInterface.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GetContractsPublicItemsContractId200Ok model module.
   * @module model/GetContractsPublicItemsContractId200Ok
   * @version 1.3.8
   */

  /**
   * Constructs a new <code>GetContractsPublicItemsContractId200Ok</code>.
   * 200 ok object
   * @alias module:model/GetContractsPublicItemsContractId200Ok
   * @class
   * @param isIncluded {Boolean} true if the contract issuer has submitted this item with the contract, false if the isser is asking for this item in the contract
   * @param quantity {Number} Number of items in the stack
   * @param recordId {Number} Unique ID for the item, used by the contract system
   * @param typeId {Number} Type ID for item
   */
  var exports = function(isIncluded, quantity, recordId, typeId) {
    this.isIncluded = isIncluded;
    this.quantity = quantity;
    this.recordId = recordId;
    this.typeId = typeId;
  };

  /**
   * Constructs a <code>GetContractsPublicItemsContractId200Ok</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetContractsPublicItemsContractId200Ok} obj Optional instance to populate.
   * @return {module:model/GetContractsPublicItemsContractId200Ok} The populated <code>GetContractsPublicItemsContractId200Ok</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('is_blueprint_copy'))
        obj.isBlueprintCopy = ApiClient.convertToType(data['is_blueprint_copy'], 'Boolean');
      if (data.hasOwnProperty('is_included'))
        obj.isIncluded = ApiClient.convertToType(data['is_included'], 'Boolean');
      if (data.hasOwnProperty('item_id'))
        obj.itemId = ApiClient.convertToType(data['item_id'], 'Number');
      if (data.hasOwnProperty('material_efficiency'))
        obj.materialEfficiency = ApiClient.convertToType(data['material_efficiency'], 'Number');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
      if (data.hasOwnProperty('record_id'))
        obj.recordId = ApiClient.convertToType(data['record_id'], 'Number');
      if (data.hasOwnProperty('runs'))
        obj.runs = ApiClient.convertToType(data['runs'], 'Number');
      if (data.hasOwnProperty('time_efficiency'))
        obj.timeEfficiency = ApiClient.convertToType(data['time_efficiency'], 'Number');
      if (data.hasOwnProperty('type_id'))
        obj.typeId = ApiClient.convertToType(data['type_id'], 'Number');
    }
    return obj;
  }

  /**
   * is_blueprint_copy boolean
   * @member {Boolean} isBlueprintCopy
   */
  exports.prototype.isBlueprintCopy = undefined;

  /**
   * true if the contract issuer has submitted this item with the contract, false if the isser is asking for this item in the contract
   * @member {Boolean} isIncluded
   */
  exports.prototype.isIncluded = undefined;

  /**
   * Unique ID for the item being sold. Not present if item is being requested by contract rather than sold with contract
   * @member {Number} itemId
   */
  exports.prototype.itemId = undefined;

  /**
   * Material Efficiency Level of the blueprint
   * @member {Number} materialEfficiency
   */
  exports.prototype.materialEfficiency = undefined;

  /**
   * Number of items in the stack
   * @member {Number} quantity
   */
  exports.prototype.quantity = undefined;

  /**
   * Unique ID for the item, used by the contract system
   * @member {Number} recordId
   */
  exports.prototype.recordId = undefined;

  /**
   * Number of runs remaining if the blueprint is a copy, -1 if it is an original
   * @member {Number} runs
   */
  exports.prototype.runs = undefined;

  /**
   * Time Efficiency Level of the blueprint
   * @member {Number} timeEfficiency
   */
  exports.prototype.timeEfficiency = undefined;

  /**
   * Type ID for item
   * @member {Number} typeId
   */
  exports.prototype.typeId = undefined;

  return exports;

}));
