/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.3.8
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetCharactersCharacterIdAgentsResearch200Ok = factory(root.EveSwaggerInterface.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GetCharactersCharacterIdAgentsResearch200Ok model module.
   * @module model/GetCharactersCharacterIdAgentsResearch200Ok
   * @version 1.3.8
   */

  /**
   * Constructs a new <code>GetCharactersCharacterIdAgentsResearch200Ok</code>.
   * 200 ok object
   * @alias module:model/GetCharactersCharacterIdAgentsResearch200Ok
   * @class
   * @param agentId {Number} agent_id integer
   * @param pointsPerDay {Number} points_per_day number
   * @param remainderPoints {Number} remainder_points number
   * @param skillTypeId {Number} skill_type_id integer
   * @param startedAt {Date} started_at string
   */
  var exports = function(agentId, pointsPerDay, remainderPoints, skillTypeId, startedAt) {
    this.agentId = agentId;
    this.pointsPerDay = pointsPerDay;
    this.remainderPoints = remainderPoints;
    this.skillTypeId = skillTypeId;
    this.startedAt = startedAt;
  };

  /**
   * Constructs a <code>GetCharactersCharacterIdAgentsResearch200Ok</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCharactersCharacterIdAgentsResearch200Ok} obj Optional instance to populate.
   * @return {module:model/GetCharactersCharacterIdAgentsResearch200Ok} The populated <code>GetCharactersCharacterIdAgentsResearch200Ok</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('agent_id'))
        obj.agentId = ApiClient.convertToType(data['agent_id'], 'Number');
      if (data.hasOwnProperty('points_per_day'))
        obj.pointsPerDay = ApiClient.convertToType(data['points_per_day'], 'Number');
      if (data.hasOwnProperty('remainder_points'))
        obj.remainderPoints = ApiClient.convertToType(data['remainder_points'], 'Number');
      if (data.hasOwnProperty('skill_type_id'))
        obj.skillTypeId = ApiClient.convertToType(data['skill_type_id'], 'Number');
      if (data.hasOwnProperty('started_at'))
        obj.startedAt = ApiClient.convertToType(data['started_at'], 'Date');
    }
    return obj;
  }

  /**
   * agent_id integer
   * @member {Number} agentId
   */
  exports.prototype.agentId = undefined;

  /**
   * points_per_day number
   * @member {Number} pointsPerDay
   */
  exports.prototype.pointsPerDay = undefined;

  /**
   * remainder_points number
   * @member {Number} remainderPoints
   */
  exports.prototype.remainderPoints = undefined;

  /**
   * skill_type_id integer
   * @member {Number} skillTypeId
   */
  exports.prototype.skillTypeId = undefined;

  /**
   * started_at string
   * @member {Date} startedAt
   */
  exports.prototype.startedAt = undefined;

  return exports;

}));
