/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.3.8
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetKillmailsKillmailIdKillmailHashItem', 'model/GetKillmailsKillmailIdKillmailHashPosition'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetKillmailsKillmailIdKillmailHashItem'), require('./GetKillmailsKillmailIdKillmailHashPosition'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashVictim = factory(root.EveSwaggerInterface.ApiClient, root.EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashItem, root.EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashPosition);
  }
}(this, function(ApiClient, GetKillmailsKillmailIdKillmailHashItem, GetKillmailsKillmailIdKillmailHashPosition) {
  'use strict';

  /**
   * The GetKillmailsKillmailIdKillmailHashVictim model module.
   * @module model/GetKillmailsKillmailIdKillmailHashVictim
   * @version 1.3.8
   */

  /**
   * Constructs a new <code>GetKillmailsKillmailIdKillmailHashVictim</code>.
   * victim object
   * @alias module:model/GetKillmailsKillmailIdKillmailHashVictim
   * @class
   * @param damageTaken {Number} How much total damage was taken by the victim 
   * @param shipTypeId {Number} The ship that the victim was piloting and was destroyed 
   */
  var exports = function(damageTaken, shipTypeId) {
    this.damageTaken = damageTaken;
    this.shipTypeId = shipTypeId;
  };

  /**
   * Constructs a <code>GetKillmailsKillmailIdKillmailHashVictim</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetKillmailsKillmailIdKillmailHashVictim} obj Optional instance to populate.
   * @return {module:model/GetKillmailsKillmailIdKillmailHashVictim} The populated <code>GetKillmailsKillmailIdKillmailHashVictim</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('alliance_id'))
        obj.allianceId = ApiClient.convertToType(data['alliance_id'], 'Number');
      if (data.hasOwnProperty('character_id'))
        obj.characterId = ApiClient.convertToType(data['character_id'], 'Number');
      if (data.hasOwnProperty('corporation_id'))
        obj.corporationId = ApiClient.convertToType(data['corporation_id'], 'Number');
      if (data.hasOwnProperty('damage_taken'))
        obj.damageTaken = ApiClient.convertToType(data['damage_taken'], 'Number');
      if (data.hasOwnProperty('faction_id'))
        obj.factionId = ApiClient.convertToType(data['faction_id'], 'Number');
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], [GetKillmailsKillmailIdKillmailHashItem]);
      if (data.hasOwnProperty('position'))
        obj.position = GetKillmailsKillmailIdKillmailHashPosition.constructFromObject(data['position']);
      if (data.hasOwnProperty('ship_type_id'))
        obj.shipTypeId = ApiClient.convertToType(data['ship_type_id'], 'Number');
    }
    return obj;
  }

  /**
   * alliance_id integer
   * @member {Number} allianceId
   */
  exports.prototype.allianceId = undefined;

  /**
   * character_id integer
   * @member {Number} characterId
   */
  exports.prototype.characterId = undefined;

  /**
   * corporation_id integer
   * @member {Number} corporationId
   */
  exports.prototype.corporationId = undefined;

  /**
   * How much total damage was taken by the victim 
   * @member {Number} damageTaken
   */
  exports.prototype.damageTaken = undefined;

  /**
   * faction_id integer
   * @member {Number} factionId
   */
  exports.prototype.factionId = undefined;

  /**
   * items array
   * @member {Array.<module:model/GetKillmailsKillmailIdKillmailHashItem>} items
   */
  exports.prototype.items = undefined;

  /**
   * @member {module:model/GetKillmailsKillmailIdKillmailHashPosition} position
   */
  exports.prototype.position = undefined;

  /**
   * The ship that the victim was piloting and was destroyed 
   * @member {Number} shipTypeId
   */
  exports.prototype.shipTypeId = undefined;

  return exports;

}));
