/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.3.8
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashItemsItem = factory(root.EveSwaggerInterface.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GetKillmailsKillmailIdKillmailHashItemsItem model module.
   * @module model/GetKillmailsKillmailIdKillmailHashItemsItem
   * @version 1.3.8
   */

  /**
   * Constructs a new <code>GetKillmailsKillmailIdKillmailHashItemsItem</code>.
   * item object
   * @alias module:model/GetKillmailsKillmailIdKillmailHashItemsItem
   * @class
   * @param flag {Number} flag integer
   * @param itemTypeId {Number} item_type_id integer
   * @param singleton {Number} singleton integer
   */
  var exports = function(flag, itemTypeId, singleton) {
    this.flag = flag;
    this.itemTypeId = itemTypeId;
    this.singleton = singleton;
  };

  /**
   * Constructs a <code>GetKillmailsKillmailIdKillmailHashItemsItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetKillmailsKillmailIdKillmailHashItemsItem} obj Optional instance to populate.
   * @return {module:model/GetKillmailsKillmailIdKillmailHashItemsItem} The populated <code>GetKillmailsKillmailIdKillmailHashItemsItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('flag'))
        obj.flag = ApiClient.convertToType(data['flag'], 'Number');
      if (data.hasOwnProperty('item_type_id'))
        obj.itemTypeId = ApiClient.convertToType(data['item_type_id'], 'Number');
      if (data.hasOwnProperty('quantity_destroyed'))
        obj.quantityDestroyed = ApiClient.convertToType(data['quantity_destroyed'], 'Number');
      if (data.hasOwnProperty('quantity_dropped'))
        obj.quantityDropped = ApiClient.convertToType(data['quantity_dropped'], 'Number');
      if (data.hasOwnProperty('singleton'))
        obj.singleton = ApiClient.convertToType(data['singleton'], 'Number');
    }
    return obj;
  }

  /**
   * flag integer
   * @member {Number} flag
   */
  exports.prototype.flag = undefined;

  /**
   * item_type_id integer
   * @member {Number} itemTypeId
   */
  exports.prototype.itemTypeId = undefined;

  /**
   * quantity_destroyed integer
   * @member {Number} quantityDestroyed
   */
  exports.prototype.quantityDestroyed = undefined;

  /**
   * quantity_dropped integer
   * @member {Number} quantityDropped
   */
  exports.prototype.quantityDropped = undefined;

  /**
   * singleton integer
   * @member {Number} singleton
   */
  exports.prototype.singleton = undefined;

  return exports;

}));
