/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.3.8
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetCharactersCharacterIdSkillsSkill', function() {
      beforeEach(function() {
        instance = new EveSwaggerInterface.GetCharactersCharacterIdSkillsSkill();
      });

      it('should create an instance of GetCharactersCharacterIdSkillsSkill', function() {
        // TODO: update the code to test GetCharactersCharacterIdSkillsSkill
        expect(instance).to.be.a(EveSwaggerInterface.GetCharactersCharacterIdSkillsSkill);
      });

      it('should have the property activeSkillLevel (base name: "active_skill_level")', function() {
        // TODO: update the code to test the property activeSkillLevel
        expect(instance).to.have.property('activeSkillLevel');
        // expect(instance.activeSkillLevel).to.be(expectedValueLiteral);
      });

      it('should have the property skillId (base name: "skill_id")', function() {
        // TODO: update the code to test the property skillId
        expect(instance).to.have.property('skillId');
        // expect(instance.skillId).to.be(expectedValueLiteral);
      });

      it('should have the property skillpointsInSkill (base name: "skillpoints_in_skill")', function() {
        // TODO: update the code to test the property skillpointsInSkill
        expect(instance).to.have.property('skillpointsInSkill');
        // expect(instance.skillpointsInSkill).to.be(expectedValueLiteral);
      });

      it('should have the property trainedSkillLevel (base name: "trained_skill_level")', function() {
        // TODO: update the code to test the property trainedSkillLevel
        expect(instance).to.have.property('trainedSkillLevel');
        // expect(instance.trainedSkillLevel).to.be(expectedValueLiteral);
      });

    });
  });

}));
