/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.3.8
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetCorporationsCorporationIdRolesHistory200Ok', function() {
      beforeEach(function() {
        instance = new EveSwaggerInterface.GetCorporationsCorporationIdRolesHistory200Ok();
      });

      it('should create an instance of GetCorporationsCorporationIdRolesHistory200Ok', function() {
        // TODO: update the code to test GetCorporationsCorporationIdRolesHistory200Ok
        expect(instance).to.be.a(EveSwaggerInterface.GetCorporationsCorporationIdRolesHistory200Ok);
      });

      it('should have the property changedAt (base name: "changed_at")', function() {
        // TODO: update the code to test the property changedAt
        expect(instance).to.have.property('changedAt');
        // expect(instance.changedAt).to.be(expectedValueLiteral);
      });

      it('should have the property characterId (base name: "character_id")', function() {
        // TODO: update the code to test the property characterId
        expect(instance).to.have.property('characterId');
        // expect(instance.characterId).to.be(expectedValueLiteral);
      });

      it('should have the property issuerId (base name: "issuer_id")', function() {
        // TODO: update the code to test the property issuerId
        expect(instance).to.have.property('issuerId');
        // expect(instance.issuerId).to.be(expectedValueLiteral);
      });

      it('should have the property newRoles (base name: "new_roles")', function() {
        // TODO: update the code to test the property newRoles
        expect(instance).to.have.property('newRoles');
        // expect(instance.newRoles).to.be(expectedValueLiteral);
      });

      it('should have the property oldRoles (base name: "old_roles")', function() {
        // TODO: update the code to test the property oldRoles
        expect(instance).to.have.property('oldRoles');
        // expect(instance.oldRoles).to.be(expectedValueLiteral);
      });

      it('should have the property roleType (base name: "role_type")', function() {
        // TODO: update the code to test the property roleType
        expect(instance).to.have.property('roleType');
        // expect(instance.roleType).to.be(expectedValueLiteral);
      });

    });
  });

}));
