/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.3.8
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetIndustrySystems200Ok', function() {
      beforeEach(function() {
        instance = new EveSwaggerInterface.GetIndustrySystems200Ok();
      });

      it('should create an instance of GetIndustrySystems200Ok', function() {
        // TODO: update the code to test GetIndustrySystems200Ok
        expect(instance).to.be.a(EveSwaggerInterface.GetIndustrySystems200Ok);
      });

      it('should have the property costIndices (base name: "cost_indices")', function() {
        // TODO: update the code to test the property costIndices
        expect(instance).to.have.property('costIndices');
        // expect(instance.costIndices).to.be(expectedValueLiteral);
      });

      it('should have the property solarSystemId (base name: "solar_system_id")', function() {
        // TODO: update the code to test the property solarSystemId
        expect(instance).to.have.property('solarSystemId');
        // expect(instance.solarSystemId).to.be(expectedValueLiteral);
      });

    });
  });

}));
