/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.3.8
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PostUiOpenwindowNewmailNewMail', function() {
      beforeEach(function() {
        instance = new EveSwaggerInterface.PostUiOpenwindowNewmailNewMail();
      });

      it('should create an instance of PostUiOpenwindowNewmailNewMail', function() {
        // TODO: update the code to test PostUiOpenwindowNewmailNewMail
        expect(instance).to.be.a(EveSwaggerInterface.PostUiOpenwindowNewmailNewMail);
      });

      it('should have the property body (base name: "body")', function() {
        // TODO: update the code to test the property body
        expect(instance).to.have.property('body');
        // expect(instance.body).to.be(expectedValueLiteral);
      });

      it('should have the property recipients (base name: "recipients")', function() {
        // TODO: update the code to test the property recipients
        expect(instance).to.have.property('recipients');
        // expect(instance.recipients).to.be(expectedValueLiteral);
      });

      it('should have the property subject (base name: "subject")', function() {
        // TODO: update the code to test the property subject
        expect(instance).to.have.property('subject');
        // expect(instance.subject).to.be(expectedValueLiteral);
      });

      it('should have the property toCorpOrAllianceId (base name: "to_corp_or_alliance_id")', function() {
        // TODO: update the code to test the property toCorpOrAllianceId
        expect(instance).to.have.property('toCorpOrAllianceId');
        // expect(instance.toCorpOrAllianceId).to.be(expectedValueLiteral);
      });

      it('should have the property toMailingListId (base name: "to_mailing_list_id")', function() {
        // TODO: update the code to test the property toMailingListId
        expect(instance).to.have.property('toMailingListId');
        // expect(instance.toMailingListId).to.be(expectedValueLiteral);
      });

    });
  });

}));
