/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.3.8
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EveSwaggerInterface.AssetsApi();
  });

  describe('(package)', function() {
    describe('AssetsApi', function() {
      describe('getCharactersCharacterIdAssets', function() {
        it('should call getCharactersCharacterIdAssets successfully', function(done) {
          // TODO: uncomment, update parameter values for getCharactersCharacterIdAssets call and complete the assertions
          /*
          var characterId = 56;
          var opts = {};
          opts.datasource = "tranquility";
          opts.ifNoneMatch = "ifNoneMatch_example";
          opts.page = 1;
          opts.token = "token_example";

          instance.getCharactersCharacterIdAssets(characterId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EveSwaggerInterface.GetCharactersCharacterIdAssets200Ok);
              expect(data.isBlueprintCopy).to.be.a('boolean');
              expect(data.isBlueprintCopy).to.be(false);
              expect(data.isSingleton).to.be.a('boolean');
              expect(data.isSingleton).to.be(false);
              expect(data.itemId).to.be.a('number');
              expect(data.itemId).to.be("0");
              expect(data.locationFlag).to.be.a('string');
              expect(data.locationFlag).to.be("AssetSafety");
              expect(data.locationId).to.be.a('number');
              expect(data.locationId).to.be("0");
              expect(data.locationType).to.be.a('string');
              expect(data.locationType).to.be("station");
              expect(data.quantity).to.be.a('number');
              expect(data.quantity).to.be(0);
              expect(data.typeId).to.be.a('number');
              expect(data.typeId).to.be(0);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCorporationsCorporationIdAssets', function() {
        it('should call getCorporationsCorporationIdAssets successfully', function(done) {
          // TODO: uncomment, update parameter values for getCorporationsCorporationIdAssets call and complete the assertions
          /*
          var corporationId = 56;
          var opts = {};
          opts.datasource = "tranquility";
          opts.ifNoneMatch = "ifNoneMatch_example";
          opts.page = 1;
          opts.token = "token_example";

          instance.getCorporationsCorporationIdAssets(corporationId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EveSwaggerInterface.GetCorporationsCorporationIdAssets200Ok);
              expect(data.isBlueprintCopy).to.be.a('boolean');
              expect(data.isBlueprintCopy).to.be(false);
              expect(data.isSingleton).to.be.a('boolean');
              expect(data.isSingleton).to.be(false);
              expect(data.itemId).to.be.a('number');
              expect(data.itemId).to.be("0");
              expect(data.locationFlag).to.be.a('string');
              expect(data.locationFlag).to.be("AssetSafety");
              expect(data.locationId).to.be.a('number');
              expect(data.locationId).to.be("0");
              expect(data.locationType).to.be.a('string');
              expect(data.locationType).to.be("station");
              expect(data.quantity).to.be.a('number');
              expect(data.quantity).to.be(0);
              expect(data.typeId).to.be.a('number');
              expect(data.typeId).to.be(0);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postCharactersCharacterIdAssetsLocations', function() {
        it('should call postCharactersCharacterIdAssetsLocations successfully', function(done) {
          // TODO: uncomment, update parameter values for postCharactersCharacterIdAssetsLocations call and complete the assertions
          /*
          var characterId = 56;
          var itemIds = [new EveSwaggerInterface.[Number]()];
          var opts = {};
          opts.datasource = "tranquility";
          opts.token = "token_example";

          instance.postCharactersCharacterIdAssetsLocations(characterId, itemIds, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EveSwaggerInterface.PostCharactersCharacterIdAssetsLocations200Ok);
              expect(data.itemId).to.be.a('number');
              expect(data.itemId).to.be("0");
              expect(data.position).to.be.a(EveSwaggerInterface.PostCharactersCharacterIdAssetsLocationsPosition);
                    expect(data.position.x).to.be.a('number');
                expect(data.position.x).to.be(0.0);
                expect(data.position.y).to.be.a('number');
                expect(data.position.y).to.be(0.0);
                expect(data.position.z).to.be.a('number');
                expect(data.position.z).to.be(0.0);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postCharactersCharacterIdAssetsNames', function() {
        it('should call postCharactersCharacterIdAssetsNames successfully', function(done) {
          // TODO: uncomment, update parameter values for postCharactersCharacterIdAssetsNames call and complete the assertions
          /*
          var characterId = 56;
          var itemIds = [new EveSwaggerInterface.[Number]()];
          var opts = {};
          opts.datasource = "tranquility";
          opts.token = "token_example";

          instance.postCharactersCharacterIdAssetsNames(characterId, itemIds, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EveSwaggerInterface.PostCharactersCharacterIdAssetsNames200Ok);
              expect(data.itemId).to.be.a('number');
              expect(data.itemId).to.be("0");
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postCorporationsCorporationIdAssetsLocations', function() {
        it('should call postCorporationsCorporationIdAssetsLocations successfully', function(done) {
          // TODO: uncomment, update parameter values for postCorporationsCorporationIdAssetsLocations call and complete the assertions
          /*
          var corporationId = 56;
          var itemIds = [new EveSwaggerInterface.[Number]()];
          var opts = {};
          opts.datasource = "tranquility";
          opts.token = "token_example";

          instance.postCorporationsCorporationIdAssetsLocations(corporationId, itemIds, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EveSwaggerInterface.PostCorporationsCorporationIdAssetsLocations200Ok);
              expect(data.itemId).to.be.a('number');
              expect(data.itemId).to.be("0");
              expect(data.position).to.be.a(EveSwaggerInterface.PostCorporationsCorporationIdAssetsLocationsPosition);
                    expect(data.position.x).to.be.a('number');
                expect(data.position.x).to.be(0.0);
                expect(data.position.y).to.be.a('number');
                expect(data.position.y).to.be(0.0);
                expect(data.position.z).to.be.a('number');
                expect(data.position.z).to.be(0.0);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postCorporationsCorporationIdAssetsNames', function() {
        it('should call postCorporationsCorporationIdAssetsNames successfully', function(done) {
          // TODO: uncomment, update parameter values for postCorporationsCorporationIdAssetsNames call and complete the assertions
          /*
          var corporationId = 56;
          var itemIds = [new EveSwaggerInterface.[Number]()];
          var opts = {};
          opts.datasource = "tranquility";
          opts.token = "token_example";

          instance.postCorporationsCorporationIdAssetsNames(corporationId, itemIds, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EveSwaggerInterface.PostCorporationsCorporationIdAssetsNames200Ok);
              expect(data.itemId).to.be.a('number');
              expect(data.itemId).to.be("0");
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
