/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.3.8
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EveSwaggerInterface.RoutesApi();
  });

  describe('(package)', function() {
    describe('RoutesApi', function() {
      describe('getRouteOriginDestination', function() {
        it('should call getRouteOriginDestination successfully', function(done) {
          // TODO: uncomment, update parameter values for getRouteOriginDestination call and complete the assertions
          /*
          var destination = 56;
          var origin = 56;
          var opts = {};
          opts.avoid = [3.4];
          opts.connections = [new EveSwaggerInterface.[Number]()];
          opts.datasource = "tranquility";
          opts.flag = "shortest";
          opts.ifNoneMatch = "ifNoneMatch_example";

          instance.getRouteOriginDestination(destination, origin, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a('number');
              // expect(data).to.be(null);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
